// Race data — edit this file to add / update races
const racesData = {
  upcoming: [
    {
      id: "u1",
      name: "Karlovy Vary Half Marathon",
      date: "2026-09-06",
      location: "Karlovy Vary, CZ",
      distance: 21.097,
      distanceLabel: "Half Marathon",
      price: 590,
      currency: "CZK",
      targetTime: "1:45:00",
      url: "https://www.kvmarathon.cz",
      notes: "Hilly course, scenic spa town"
    },
    {
      id: "u2",
      name: "Prague International Marathon",
      date: "2026-10-18",
      location: "Prague, CZ",
      distance: 42.195,
      distanceLabel: "Marathon",
      price: 1990,
      currency: "CZK",
      targetTime: "3:45:00",
      url: "https://www.runczech.com",
      notes: "Sub-4 goal race"
    },
    {
      id: "u3",
      name: "Silvestrovský běh Praha",
      date: "2026-12-31",
      location: "Prague, CZ",
      distance: 5,
      distanceLabel: "5 km",
      price: 200,
      currency: "CZK",
      targetTime: "0:22:00",
      url: "",
      notes: "Fun New Year's Eve run"
    }
  ],
  past: [
    {
      id: "p1",
      name: "RunCzech Running League – 5 km",
      date: "2025-04-10",
      location: "Prague, CZ",
      distance: 5,
      distanceLabel: "5 km",
      price: 350,
      currency: "CZK",
      targetTime: "0:24:00",
      chipTime: "0:23:41",
      gunTime: "0:24:02",
      position: 87,
      totalParticipants: 312,
      bib: "D204",
      url: "",
      notes: ""
    },
    {
      id: "p2",
      name: "Mattoni Ústí nad Labem Half Marathon",
      date: "2025-06-15",
      location: "Ústí nad Labem, CZ",
      distance: 21.097,
      distanceLabel: "Half Marathon",
      price: 690,
      currency: "CZK",
      targetTime: "1:50:00",
      chipTime: "1:52:34",
      gunTime: "1:53:07",
      position: 224,
      totalParticipants: 890,
      bib: "B881",
      url: "https://www.mattoni-hnm.cz",
      notes: "Slightly over target, warm conditions"
    },
    {
      id: "p3",
      name: "Mattoni Praha Half Marathon",
      date: "2025-03-29",
      location: "Prague, CZ",
      distance: 21.097,
      distanceLabel: "Half Marathon",
      price: 1250,
      currency: "CZK",
      targetTime: "1:52:00",
      chipTime: "1:51:09",
      gunTime: "1:52:44",
      position: 1103,
      totalParticipants: 5400,
      bib: "A3315",
      url: "https://www.runczech.com",
      notes: "PB! Flat, fast course"
    },
    {
      id: "p4",
      name: "RunCzech Running League – 10 km",
      date: "2024-10-03",
      location: "Prague, CZ",
      distance: 10,
      distanceLabel: "10 km",
      price: 450,
      currency: "CZK",
      targetTime: "0:50:00",
      chipTime: "0:49:22",
      gunTime: "0:49:58",
      position: 143,
      totalParticipants: 540,
      bib: "C512",
      url: "",
      notes: "First sub-50 10 km!"
    },
    {
      id: "p5",
      name: "Volkswagen Prague Marathon",
      date: "2024-05-05",
      location: "Prague, CZ",
      distance: 42.195,
      distanceLabel: "Marathon",
      price: 2200,
      currency: "CZK",
      targetTime: "4:00:00",
      chipTime: "4:03:52",
      gunTime: "4:07:18",
      position: 2841,
      totalParticipants: 8200,
      bib: "E1027",
      url: "https://www.runczech.com",
      notes: "First marathon — just missed sub-4"
    },
    {
      id: "p6",
      name: "Pražský půlmaraton",
      date: "2024-03-24",
      location: "Prague, CZ",
      distance: 21.097,
      distanceLabel: "Half Marathon",
      price: 1050,
      currency: "CZK",
      targetTime: "2:00:00",
      chipTime: "1:58:14",
      gunTime: "2:00:31",
      position: 1544,
      totalParticipants: 5600,
      bib: "A4921",
      url: "https://www.runczech.com",
      notes: "First sub-2 half marathon!"
    }
  ]
};
