// Race data — edit this file to add / update races
const racesData = {
  upcoming: [
    {
      id: "u1",
      name: "Birell 10K Night Race Prague 2026",
      date: "2026-09-05",
      location: "Prague, CZ",
      distance: 10,
      distanceLabel: "10 km",
      price: 675,
      currency: "CZK",
      targetTime: "00:49:00",
      url: "https://www.runczech.com/en/events/birell-10k-night-race-prague-2026",
      notes: ""
    },
    {
      id: "u2",
      name: "NN Night Run Praha 2026",
      date: "2026-09-12",
      location: "Praha, CZ",
      distance: 10,
      distanceLabel: "10 km",
      price: 0,
      currency: "CZK",
      targetTime: "00:49:00",
      url: "https://night-run.cz/zavody/-326-nn-night-run-praha.html",
      notes: ""
    },
    {
      id: "u3",
      name: "Trebonsky pulmaraton 2026",
      date: "2026-10-03",
      location: "Trebon, CZ",
      distance: 21.097,
      distanceLabel: "Half Marathon",
      price: 997,
      currency: "CZK",
      targetTime: "01:50:00",
      url: "https://www.bez.cz/startovne/puma-trebonsky-pul-maraton--desitka-a-petka-2026/",
      notes: ""
    },
    {
      id: "u4",
      name: "CEZ RunTour Pardubice 2026",
      date: "2026-10-17",
      location: "Pardubice, CZ",
      distance: 10,
      distanceLabel: "10 km",
      price: 560,
      currency: "CZK",
      targetTime: "00:49:00",
      url: "https://www.run-tour.cz/cs/kalendar/pardubice",
      notes: ""
    }
  ],
  past: [
    {
      id: "p1",
      name: "Mattoni Half Marathon Karlovy Vary 2025",
      date: "2025-05-17",
      location: "Karlovy Vary, CZ",
      distance: 21.097,
      distanceLabel: "Half Marathon",
      price: 825,
      currency: "CZK",
      targetTime: "02:00:00",
      chipTime: "01:57:34",
      gunTime: "01:59:00",
      position: 1316,
      bib: "2442",
      url: "https://www.runczech.com/en/events/mattoni-karlovy-vary-running-festival-2025",
      notes: ""
    },
    {
      id: "p2",
      name: "Mattoni Usti nad Labem Half Marathon 2025",
      date: "2025-09-20",
      location: "Usti nad Labem, CZ",
      distance: 21.097,
      distanceLabel: "Half Marathon",
      price: 825,
      currency: "CZK",
      targetTime: "02:00:00",
      chipTime: "02:14:57",
      gunTime: "",
      position: 1557,
      bib: "2029",
      url: "https://www.runczech.com/en/events/mattoni-usti-nad-labem-running-2025",
      notes: ""
    },
    {
      id: "p3",
      name: "Generali Prague Half Marathon 2026",
      date: "2026-03-28",
      location: "Prague, CZ",
      distance: 21.097,
      distanceLabel: "Half Marathon",
      price: 1650,
      currency: "CZK",
      targetTime: "02:00:00",
      chipTime: "01:59:09",
      gunTime: "",
      position: 8331,
      bib: "5982",
      url: "https://www.runczech.com/en/result-detail?result_id=1251062",
      notes: ""
    },
    {
      id: "p4",
      name: "Vodafone Prague Marathon 2026",
      date: "2026-05-03",
      location: "Prague, CZ",
      distance: 42.195,
      distanceLabel: "Marathon",
      price: 2575,
      currency: "CZK",
      targetTime: "04:00:00",
      chipTime: "05:51:05",
      gunTime: "",
      position: 8691,
      bib: "5893",
      url: "https://www.runczech.com/en/result-detail?result_id=1388880",
      notes: ""
    },
    {
      id: "p5",
      name: "Mattoni Half Marathon Ceske Budejovice 2026",
      date: "2026-05-30",
      location: "Ceske Budejovice, CZ",
      distance: 21.097,
      distanceLabel: "Half Marathon",
      price: 725,
      currency: "CZK",
      targetTime: "01:55:00",
      chipTime: "01:55:33",
      gunTime: "",
      position: 1552,
      bib: "1864",
      url: "https://www.runczech.com/en/result-detail?result_id=1425434",
      notes: ""
    },
    {
      id: "p6",
      name: "CEZ Run Praha 10 km 2025",
      date: "2025-02-08",
      location: "Prague, CZ",
      distance: 10,
      distanceLabel: "10 km",
      price: 650,
      currency: "CZK",
      targetTime: "00:55:00",
      chipTime: "00:52:55",
      gunTime: "",
      position: 287,
      bib: "1231",
      url: "https://www.run-tour.cz/cs/vysledky/?f=flt&uq=bb27230c431078395e133b47fc4a0609&race_yr=",
      notes: ""
    },
    {
      id: "p7",
      name: "CEZ Christmas Night Run Praha 2024",
      date: "2024-12-14",
      location: "Prague, CZ",
      distance: 5,
      distanceLabel: "5 km",
      price: 650,
      currency: "CZK",
      targetTime: "00:40:00",
      chipTime: "00:31:33",
      gunTime: "",
      position: 348,
      bib: "",
      url: "",
      notes: ""
    },
    {
      id: "p8",
      name: "Intersport Christmas Night Run Praha 2025",
      date: "2025-12-13",
      location: "Prague, CZ",
      distance: 5,
      distanceLabel: "5 km",
      price: 0,
      currency: "CZK",
      targetTime: "00:30:00",
      chipTime: "00:28:31",
      gunTime: "",
      position: 218,
      bib: "",
      url: "",
      notes: ""
    },
    {
      id: "p9",
      name: "NN Night Run 2024",
      date: "2024-10-19",
      location: "Prague, CZ",
      distance: 10,
      distanceLabel: "10 km",
      price: 0,
      currency: "CZK",
      targetTime: "01:30:00",
      chipTime: "01:11:57",
      gunTime: "",
      position: 399,
      bib: "",
      url: "",
      notes: ""
    },
    {
      id: "p10",
      name: "Jindrichohradecky pulmaraton - relay 2026",
      date: "2026-06-13",
      location: "Jindrichuv Hradec, CZ",
      distance: 10.5485,
      distanceLabel: "Relay (half of half marathon)",
      price: 0,
      currency: "CZK",
      targetTime: "00:55:00",
      chipTime: "00:56:43",
      gunTime: "",
      position: 28,
      bib: "302",
      url: "",
      notes: "Stafeta Pat a Mat"
    }
  ]
};
